# Generated by Django 2.2.4 on 2019-08-26 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('source', models.IntegerField(db_index=True, verbose_name='来源网站ID')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_hotspot',
            },
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='来源ID')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
                ('name', models.CharField(max_length=20, verbose_name='榜名')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='来源URL')),
                ('fetch_interval', models.IntegerField(default=10, verbose_name='采集频率')),
                ('fetch_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址')),
                ('last_runtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后运行时间')),
                ('abnormal', models.IntegerField(default=0, verbose_name='异常代码')),
                ('warn_msg', models.CharField(blank=True, max_length=200, null=True, verbose_name='异常提醒')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'config_source',
            },
        ),
    ]
