# Generated by Django 2.2.4 on 2019-08-29 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='real_pos',
            field=models.IntegerField(default=10, verbose_name='实时热度'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='default_count',
            field=models.IntegerField(default=10, verbose_name='默认返回条数'),
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('rank', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SourceItem', verbose_name='来源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增历史ID')),
                ('source', models.IntegerField(verbose_name='来源')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增收藏ID')),
                ('source', models.IntegerField(verbose_name='来源')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
