# Generated by Django 2.2.4 on 2019-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sourceitem_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='来源网站'),
        ),
    ]
