# Generated by Django 2.2.4 on 2019-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sourceitem_site_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={'verbose_name': '采集数据', 'verbose_name_plural': '采集数据'},
        ),
        migrations.AlterModelOptions(
            name='sourceitem',
            options={'verbose_name': '热点源', 'verbose_name_plural': '热点源'},
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='charset',
            field=models.CharField(default='utf-8', max_length=5, verbose_name='网站编码'),
        ),
    ]
