# Generated by Django 2.2.4 on 2019-08-31 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190830_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志自增id')),
                ('source_id', models.IntegerField(verbose_name='来源ID')),
                ('hot_num', models.IntegerField(verbose_name='热点数量')),
                ('upload_num', models.IntegerField(verbose_name='上次成功数量')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '采集日志',
                'verbose_name_plural': '采集日志',
                'db_table': 'data_log_website',
            },
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '用户历史浏览', 'verbose_name_plural': '用户历史浏览'},
        ),
        migrations.AlterModelOptions(
            name='useritem',
            options={'verbose_name': '用户热点源', 'verbose_name_plural': '用户热点源'},
        ),
        migrations.AlterModelTable(
            name='collection',
            table='data_user_collect',
        ),
        migrations.AlterModelTable(
            name='history',
            table='data_user_history',
        ),
        migrations.AlterModelTable(
            name='useritem',
            table='data_user',
        ),
    ]
